### ISSUE TITLE
Errors do not show up in the scroll bar

### ISSUE THREAD

**Issue by rooslucas** [adebesin/spacemacs#1]
When I use PyCharm with the default *Dracula* theme, I see yellow/red marks in the scroll bar that indicate where errors are in my file. However, I can't see them when I use this *Spacemacs* theme, which is very inconvenient to me.

Expected result: The yellow/red error marks show up in the scroll bar when using *Spacemacs*
Actual result: They do not show up

**Comment by adebesin** [comment]
thanks.. will fix this asap
